"""add indexes to task table

Revision ID: 035d8103cf9f
Revises: b97891b59185
Create Date: 2026-07-15 10:21:02.917688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035d8103cf9f'
down_revision: Union[str, Sequence[str], None] = 'b97891b59185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_assignee_id'), 'task', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_task_author_id'), 'task', ['author_id'], unique=False)
    op.create_index(op.f('ix_task_creation_date'), 'task', ['creation_date'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_status_id'), 'task', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_id'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_task_creation_date'), table_name='task')
    op.drop_index(op.f('ix_task_author_id'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_id'), table_name='task')
    # ### end Alembic commands ###
