"""add zakaz table

Revision ID: 175d63704a08
Revises: 79843ede7f69
Create Date: 2026-08-31 16:22:51.732818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '175d63704a08'
down_revision: Union[str, Sequence[str], None] = '79843ede7f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zakaz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ord_date', sa.Date(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('delivery_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anketa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anketa_id'], ['partner_application.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakaz_anketa_id'), 'zakaz', ['anketa_id'], unique=False)
    op.create_index(op.f('ix_zakaz_num'), 'zakaz', ['num'], unique=False)
    op.create_index(op.f('ix_zakaz_ord_date'), 'zakaz', ['ord_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakaz_ord_date'), table_name='zakaz')
    op.drop_index(op.f('ix_zakaz_num'), table_name='zakaz')
    op.drop_index(op.f('ix_zakaz_anketa_id'), table_name='zakaz')
    op.drop_table('zakaz')
    # ### end Alembic commands ###
