"""add application_states table, rework partner_application claimed/status fields, add client_ip/user_agent

Revision ID: 1ccf58ff5402
Revises: ead2a8f54d1c
Create Date: 2026-08-18 10:14:18.008406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ccf58ff5402'
down_revision: Union[str, Sequence[str], None] = 'ead2a8f54d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_states_name'), 'application_states', ['name'], unique=True)

    application_states_table = sa.table(
        'application_states',
        sa.column('name', sqlmodel.sql.sqltypes.AutoString()),
    )
    op.bulk_insert(application_states_table, [
        {'name': 'новая'},
        {'name': 'на рассмотрении'},
        {'name': 'подтверждена'},
        {'name': 'под вопросом'},
        {'name': 'не подтверждена'},
    ])

    # NOTE: hand-adjusted from the raw autogenerate output to use batch mode
    # for the partner_application alterations — SQLite has no ALTER support
    # for adding/dropping constraints outside batch mode
    # (op.create_foreign_key/op.drop_constraint fail with NotImplementedError
    # on SQLite otherwise); batch_alter_table works transparently on Postgres
    # too (it just issues plain ALTER statements there, no table rebuild).
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_partner_application_review_status'))
        batch_op.create_index(batch_op.f('ix_partner_application_claimed_type_id'), ['claimed_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_application_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_application_status_id'), ['status_id'], unique=False)
        batch_op.create_foreign_key('fk_partner_application_claimed_type_id_firm_type', 'firm_type', ['claimed_type_id'], ['id'])
        batch_op.create_foreign_key('fk_partner_application_status_id_application_states', 'application_states', ['status_id'], ['id'])
        batch_op.drop_column('claimed_status')
        batch_op.drop_column('review_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.VARCHAR(), server_default=sa.text("'новая'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('claimed_status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_partner_application_status_id_application_states', type_='foreignkey')
        batch_op.drop_constraint('fk_partner_application_claimed_type_id_firm_type', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_partner_application_status_id'))
        batch_op.drop_index(batch_op.f('ix_partner_application_client_ip'))
        batch_op.drop_index(batch_op.f('ix_partner_application_claimed_type_id'))
        batch_op.create_index(batch_op.f('ix_partner_application_review_status'), ['review_status'], unique=False)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('client_ip')
        batch_op.drop_column('status_id')
        batch_op.drop_column('claimed_type_id')
    op.drop_index(op.f('ix_application_states_name'), table_name='application_states')
    op.drop_table('application_states')
    # ### end Alembic commands ###
