"""add firm_price_body table

Revision ID: 1ff96f73e59f
Revises: 9e9b8206a35d
Create Date: 2026-07-23 09:21:03.441332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff96f73e59f'
down_revision: Union[str, Sequence[str], None] = '9e9b8206a35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_price_body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['firm_goods.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['firm_price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_id', 'good_id', name='uq_firm_price_body_price_id_good_id')
    )
    op.create_index(op.f('ix_firm_price_body_good_id'), 'firm_price_body', ['good_id'], unique=False)
    op.create_index(op.f('ix_firm_price_body_price_id'), 'firm_price_body', ['price_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_price_body_price_id'), table_name='firm_price_body')
    op.drop_index(op.f('ix_firm_price_body_good_id'), table_name='firm_price_body')
    op.drop_table('firm_price_body')
    # ### end Alembic commands ###
