"""add firm_goods table

Revision ID: 2229d97cae3f
Revises: 57f2c7bbb187
Create Date: 2026-07-23 09:03:50.915634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2229d97cae3f'
down_revision: Union[str, Sequence[str], None] = '57f2c7bbb187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('article', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'article', name='uq_firm_goods_firm_id_article')
    )
    op.create_index(op.f('ix_firm_goods_article'), 'firm_goods', ['article'], unique=False)
    op.create_index(op.f('ix_firm_goods_firm_id'), 'firm_goods', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firm_goods_name'), 'firm_goods', ['name'], unique=False)
    op.create_index(op.f('ix_firm_goods_unit_id'), 'firm_goods', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_goods_unit_id'), table_name='firm_goods')
    op.drop_index(op.f('ix_firm_goods_name'), table_name='firm_goods')
    op.drop_index(op.f('ix_firm_goods_firm_id'), table_name='firm_goods')
    op.drop_index(op.f('ix_firm_goods_article'), table_name='firm_goods')
    op.drop_table('firm_goods')
    # ### end Alembic commands ###
