"""create firm table

Revision ID: 27089219faf6
Revises: ce6c6202b440
Create Date: 2026-07-16 15:13:14.673489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27089219faf6'
down_revision: Union[str, Sequence[str], None] = 'ce6c6202b440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['firm_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_city_id'), 'firm', ['city_id'], unique=False)
    op.create_index(op.f('ix_firm_creation_date'), 'firm', ['creation_date'], unique=False)
    op.create_index(op.f('ix_firm_type_id'), 'firm', ['type_id'], unique=False)
    op.create_index(op.f('ix_firm_user_id'), 'firm', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_user_id'), table_name='firm')
    op.drop_index(op.f('ix_firm_type_id'), table_name='firm')
    op.drop_index(op.f('ix_firm_creation_date'), table_name='firm')
    op.drop_index(op.f('ix_firm_city_id'), table_name='firm')
    op.drop_table('firm')
    # ### end Alembic commands ###
