"""add verification_notes, verified_by, last_changed to partner_application

Revision ID: 38a81a3660c5
Revises: ecfbade8bd52
Create Date: 2026-08-21 11:38:29.849743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38a81a3660c5'
down_revision: Union[str, Sequence[str], None] = 'ecfbade8bd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-adjusted from the raw autogenerate output to use batch mode
    # for the partner_application alterations — SQLite has no ALTER support
    # for adding a foreign key constraint outside batch mode
    # (op.create_foreign_key fails with NotImplementedError on SQLite
    # otherwise); batch_alter_table works transparently on Postgres too (it
    # just issues plain ALTER statements there, no table rebuild). Also
    # hand-adjusted the server_default for last_changed: autogenerate (run
    # against Postgres) captured the Postgres-only literal sa.text('now()'),
    # which is not a valid SQLite function — replaced with the portable
    # sa.text('CURRENT_TIMESTAMP') used elsewhere in this project for the
    # equivalent func.now()-defaulted datetime columns.
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_changed', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.create_index(batch_op.f('ix_partner_application_verified_by'), ['verified_by'], unique=False)
        batch_op.create_foreign_key('fk_partner_application_verified_by_user', 'user', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partner_application_verified_by_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_partner_application_verified_by'))
        batch_op.drop_column('last_changed')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_notes')
    # ### end Alembic commands ###
