"""add isactive column to user

Revision ID: 3ab98c2f7112
Revises: a47fea42c17b
Create Date: 2026-07-08 16:43:51.769576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab98c2f7112'
down_revision: Union[str, Sequence[str], None] = 'a47fea42c17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isactive', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isactive')
    # ### end Alembic commands ###
