"""add channel_type table

Revision ID: 4c60c39b3918
Revises: a0dc855087ec
Create Date: 2026-08-10 12:52:28.415307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c60c39b3918'
down_revision: Union[str, Sequence[str], None] = 'a0dc855087ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_input', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_output', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_type_name'), 'channel_type', ['name'], unique=True)
    # ### end Alembic commands ###

    channel_type_table = sa.table(
        'channel_type',
        sa.column('name', sqlmodel.sql.sqltypes.AutoString()),
        sa.column('is_active', sa.Boolean()),
        sa.column('is_input', sa.Boolean()),
        sa.column('is_output', sa.Boolean()),
        sa.column('icon_url', sqlmodel.sql.sqltypes.AutoString()),
    )
    op.bulk_insert(channel_type_table, [
        {'name': 'person', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/person.svg'},
        {'name': 'e-mail', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/email.svg'},
        {'name': 'viber', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/viber.svg'},
        {'name': 'whatsapp', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/whatsapp.svg'},
        {'name': 'telegram', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/telegram.svg'},
        {'name': 'instagram', 'is_active': True, 'is_input': True, 'is_output': True, 'icon_url': '/pic/instagram.svg'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_type_name'), table_name='channel_type')
    op.drop_table('channel_type')
    # ### end Alembic commands ###
