"""add firm_event table

Revision ID: 5611cf1d9eab
Revises: b3553a7f0eff
Create Date: 2026-08-10 13:46:36.521175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5611cf1d9eab'
down_revision: Union[str, Sequence[str], None] = 'b3553a7f0eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['firm_channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_event_channel_id'), 'firm_event', ['channel_id'], unique=False)
    op.create_index(op.f('ix_firm_event_user_id'), 'firm_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_event_user_id'), table_name='firm_event')
    op.drop_index(op.f('ix_firm_event_channel_id'), table_name='firm_event')
    op.drop_table('firm_event')
    # ### end Alembic commands ###
