"""add constants table

Revision ID: 57f2c7bbb187
Revises: ef39cd72ebbf
Create Date: 2026-07-23 08:52:06.514529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57f2c7bbb187'
down_revision: Union[str, Sequence[str], None] = 'ef39cd72ebbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constants_name'), 'constants', ['name'], unique=True)
    op.create_index(op.f('ix_constants_updated'), 'constants', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_constants_updated'), table_name='constants')
    op.drop_index(op.f('ix_constants_name'), table_name='constants')
    op.drop_table('constants')
    # ### end Alembic commands ###
