"""add client_ip to login_info

Revision ID: 64f8fb66be42
Revises: 8e6fc4ea3b96
Create Date: 2026-07-24 16:16:49.390753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64f8fb66be42'
down_revision: Union[str, Sequence[str], None] = '8e6fc4ea3b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_info', sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_login_info_client_ip'), 'login_info', ['client_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_info_client_ip'), table_name='login_info')
    op.drop_column('login_info', 'client_ip')
    # ### end Alembic commands ###
