"""create bug and notification tables

Revision ID: 6de2fad05329
Revises: fe18170f1e74
Create Date: 2026-07-15 12:22:20.372048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6de2fad05329'
down_revision: Union[str, Sequence[str], None] = 'fe18170f1e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('isopen', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_creation_date'), 'bug', ['creation_date'], unique=False)
    op.create_index(op.f('ix_bug_reporter_id'), 'bug', ['reporter_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_creation_date'), 'notification', ['creation_date'], unique=False)
    op.create_index(op.f('ix_notification_creator_id'), 'notification', ['creator_id'], unique=False)
    op.create_index(op.f('ix_notification_receiver_id'), 'notification', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_receiver_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_creator_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_creation_date'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_bug_reporter_id'), table_name='bug')
    op.drop_index(op.f('ix_bug_creation_date'), table_name='bug')
    op.drop_table('bug')
    # ### end Alembic commands ###
