"""split social_media into instagram, facebook, linkedin

Revision ID: 79843ede7f69
Revises: 38a81a3660c5
Create Date: 2026-08-21 15:23:10.714930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79843ede7f69'
down_revision: Union[str, Sequence[str], None] = '38a81a3660c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-adjusted to use batch mode, same precedent as
    # 38a81a3660c5 — batch_alter_table works transparently on Postgres too
    # (plain ALTER statements there, no table rebuild), but is needed for
    # SQLite compatibility.
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('facebook', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('social_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
    # ### end Alembic commands ###
