"""add login_info table

Revision ID: 8e6fc4ea3b96
Revises: 1ff96f73e59f
Create Date: 2026-07-24 16:06:25.729869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e6fc4ea3b96'
down_revision: Union[str, Sequence[str], None] = '1ff96f73e59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_info_created'), 'login_info', ['created'], unique=False)
    op.create_index(op.f('ix_login_info_user_id'), 'login_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_info_user_id'), table_name='login_info')
    op.drop_index(op.f('ix_login_info_created'), table_name='login_info')
    op.drop_table('login_info')
    # ### end Alembic commands ###
