"""add firm_price table

Revision ID: 9e9b8206a35d
Revises: 2229d97cae3f
Create Date: 2026-07-23 09:14:29.811058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e9b8206a35d'
down_revision: Union[str, Sequence[str], None] = '2229d97cae3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('rem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_price_created'), 'firm_price', ['created'], unique=False)
    op.create_index(op.f('ix_firm_price_firm_id'), 'firm_price', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_price_firm_id'), table_name='firm_price')
    op.drop_index(op.f('ix_firm_price_created'), table_name='firm_price')
    op.drop_table('firm_price')
    # ### end Alembic commands ###
