"""make zakaz.num unique, index zakaz.city_id

Revision ID: a03c48c04440
Revises: 175d63704a08
Create Date: 2026-08-31 16:36:29.467953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03c48c04440'
down_revision: Union[str, Sequence[str], None] = '175d63704a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakaz_num'), table_name='zakaz')
    op.create_index(op.f('ix_zakaz_num'), 'zakaz', ['num'], unique=True)
    op.create_index(op.f('ix_zakaz_city_id'), 'zakaz', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakaz_city_id'), table_name='zakaz')
    op.drop_index(op.f('ix_zakaz_num'), table_name='zakaz')
    op.create_index(op.f('ix_zakaz_num'), 'zakaz', ['num'], unique=False)
    # ### end Alembic commands ###
