"""add firm_comment table

Revision ID: a0dc855087ec
Revises: da09c2154765
Create Date: 2026-08-10 12:14:03.557706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0dc855087ec'
down_revision: Union[str, Sequence[str], None] = 'da09c2154765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_comment_added'), 'firm_comment', ['added'], unique=False)
    op.create_index(op.f('ix_firm_comment_firm_id'), 'firm_comment', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firm_comment_user_id'), 'firm_comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_comment_user_id'), table_name='firm_comment')
    op.drop_index(op.f('ix_firm_comment_firm_id'), table_name='firm_comment')
    op.drop_index(op.f('ix_firm_comment_added'), table_name='firm_comment')
    op.drop_table('firm_comment')
    # ### end Alembic commands ###
