"""create role table

Revision ID: a752b55b2615
Revises: 2948b0153239
Create Date: 2026-07-08 12:40:53.450255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a752b55b2615'
down_revision: Union[str, Sequence[str], None] = '2948b0153239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###

    role_table = sa.table('role', sa.column('name', sqlmodel.sql.sqltypes.AutoString()))
    op.bulk_insert(role_table, [
        {'name': 'admin'},
        {'name': 'sales'},
        {'name': 'fin'},
        {'name': 'director'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
