"""add firm_channel table

Revision ID: b3553a7f0eff
Revises: d8d1fa7fe974
Create Date: 2026-08-10 13:22:08.478659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3553a7f0eff'
down_revision: Union[str, Sequence[str], None] = 'd8d1fa7fe974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_type.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_channel_channel_id'), 'firm_channel', ['channel_id'], unique=False)
    op.create_index(op.f('ix_firm_channel_firm_id'), 'firm_channel', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_channel_firm_id'), table_name='firm_channel')
    op.drop_index(op.f('ix_firm_channel_channel_id'), table_name='firm_channel')
    op.drop_table('firm_channel')
    # ### end Alembic commands ###
