"""create search source reference tables

Revision ID: ce6c6202b440
Revises: dea309ced5a4
Create Date: 2026-07-16 14:40:25.329240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce6c6202b440'
down_revision: Union[str, Sequence[str], None] = 'dea309ced5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('important', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_category_key'), 'search_category', ['key'], unique=True)
    op.create_table('search_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_source_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_source_note_key'), 'search_source_note', ['key'], unique=True)
    op.create_table('search_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('query_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('try_direct_fetch', sa.Boolean(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['search_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_directory_category_id'), 'search_directory', ['category_id'], unique=False)
    op.create_table('search_engine_query_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['search_engine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_engine_query_template_engine_id'), 'search_engine_query_template', ['engine_id'], unique=False)
    op.create_table('search_marketplace_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['search_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_marketplace_note_category_id'), 'search_marketplace_note', ['category_id'], unique=False)
    op.create_table('search_query_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['search_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_query_template_category_id'), 'search_query_template', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_query_template_category_id'), table_name='search_query_template')
    op.drop_table('search_query_template')
    op.drop_index(op.f('ix_search_marketplace_note_category_id'), table_name='search_marketplace_note')
    op.drop_table('search_marketplace_note')
    op.drop_index(op.f('ix_search_engine_query_template_engine_id'), table_name='search_engine_query_template')
    op.drop_table('search_engine_query_template')
    op.drop_index(op.f('ix_search_directory_category_id'), table_name='search_directory')
    op.drop_table('search_directory')
    op.drop_index(op.f('ix_search_source_note_key'), table_name='search_source_note')
    op.drop_table('search_source_note')
    op.drop_table('search_engine')
    op.drop_index(op.f('ix_search_category_key'), table_name='search_category')
    op.drop_table('search_category')
    # ### end Alembic commands ###
