"""add rating to firm

Revision ID: da09c2154765
Revises: 64f8fb66be42
Create Date: 2026-08-10 11:59:49.648608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da09c2154765'
down_revision: Union[str, Sequence[str], None] = '64f8fb66be42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firm', sa.Column('rating', sa.Integer(), server_default='5', nullable=False))
    op.create_index(op.f('ix_firm_rating'), 'firm', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_rating'), table_name='firm')
    op.drop_column('firm', 'rating')
    # ### end Alembic commands ###
