"""add partner_application table

Revision ID: ead2a8f54d1c
Revises: 5611cf1d9eab
Create Date: 2026-08-18 09:52:42.716169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ead2a8f54d1c'
down_revision: Union[str, Sequence[str], None] = '5611cf1d9eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claimed_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_other', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_physical_office', sa.Boolean(), nullable=True),
    sa.Column('projects_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('projects_count', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wants_discount', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('wants_sample', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), server_default='новая', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_application_city_id'), 'partner_application', ['city_id'], unique=False)
    op.create_index(op.f('ix_partner_application_created'), 'partner_application', ['created'], unique=False)
    op.create_index(op.f('ix_partner_application_review_status'), 'partner_application', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_application_review_status'), table_name='partner_application')
    op.drop_index(op.f('ix_partner_application_created'), table_name='partner_application')
    op.drop_index(op.f('ix_partner_application_city_id'), table_name='partner_application')
    op.drop_table('partner_application')
    # ### end Alembic commands ###
