"""add social_media, years_in_business, team_size, current_brands, tax_id to partner_application

Revision ID: ecfbade8bd52
Revises: 1ccf58ff5402
Create Date: 2026-08-21 11:02:12.228342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecfbade8bd52'
down_revision: Union[str, Sequence[str], None] = '1ccf58ff5402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_application', sa.Column('social_media', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner_application', sa.Column('years_in_business', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner_application', sa.Column('team_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner_application', sa.Column('current_brands', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner_application', sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_application', 'tax_id')
    op.drop_column('partner_application', 'current_brands')
    op.drop_column('partner_application', 'team_size')
    op.drop_column('partner_application', 'years_in_business')
    op.drop_column('partner_application', 'social_media')
    # ### end Alembic commands ###
