"""create unit table

Revision ID: ef39cd72ebbf
Revises: 27089219faf6
Create Date: 2026-07-23 08:25:23.904362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef39cd72ebbf'
down_revision: Union[str, Sequence[str], None] = '27089219faf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_name'), 'unit', ['name'], unique=True)
    # ### end Alembic commands ###

    unit_table = sa.table('unit', sa.column('name', sqlmodel.sql.sqltypes.AutoString()))
    op.bulk_insert(unit_table, [
        {'name': 'шт'},
        {'name': 'м'},
        {'name': 'м2'},
        {'name': 'мм'},
        {'name': 'л'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_name'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
